service: yempo-aws-nodejs

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1

functions:
  fetchLastNames:
    handler: src/handlers/fetchLastNames.handler
    events:
      - http:
          path: /lastNames
          method: get
